name: Build ASVS for Export

on:
  push:
    branches: [ github-actions ]

jobs:
  build-5:
    runs-on: ubuntu-latest

    container:
      image: crossdiver/asvs-document-builder:latest
      env:
        TARGET: 5.0
      volumes:
        - 5.0:/data
        - docker:/scripts

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          make 5.0-clean
          make 5.0

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
